[Variables]

fontname=FiraCode
dockfontsize=12
lineheight=13
fontcolor=255,255,255,200
hovercolor=255,255,255,255

backgroundcolor=10,10,10,120

desktoppath=C:\Users\lucas\Desktop
rainmeterpath=D:\Program Files\Rainmeter\Rainmeter.exe

;Valid values are Blur, Acrylic, and None
blurtype=Blur
;Type of information to sort the entries by. Valid values are: Name, Size, Type, Date.
sorttype=Type

;Dock
dockheight=30
iconsize=17

;Locations
songplace=0
binplace=50

ramplace=350
cpuplace=450

chromeplace=2130
cmderplace=2100

dayplace=2300
clockplace=2510

;Hide Elements
hidesong=1
hidechrome=0
hidecmder=0
hidebin=0
hidetime=0
hideday=0
hidecpu=0
