[Variables]

fontname=FiraCode
dockfontsize=12
lineheight=13
fontcolor=255,255,255,200
hovercolor=255,255,255,255

backgroundcolor=40, 44, 52, 255
secondarycolor=44, 49, 60, 255

desktoppath=%USERPROFILE%\Desktop

;Program paths
chromepath=["C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"]
cmdrpath=["D:\Program Files\Cmder\Cmder.exe"]

;Valid values are Blur, Acrylic, and None
blurtype=None
;Type of information to sort the entries by. Valid values are: Name, Size, Type, Date.
sorttype=Type

;Dock
dockheight=30
iconsize=17

;Locations
songplace=0
binplace=50

ramplace=350
cpuplace=450

chromeplace=2130
cmderplace=2100

dayplace=2300
clockplace=2500

;Hide Elements
hidesong=1
hidechrome=0
hidecmder=0
hidebin=0
hidetime=0
hideday=0
hidecpu=0