[Variables]

fontname=Fira Code Nerd Font
fontnamefile=Fira Code Nerd Font Mono
dockfontsize=11
lineheight=13
fontcolor=255,255,255,200
hovercolor=255,255,255,255

backgroundcolor=10,10,10,120
backgroundcolorheader=30,30,30,120

desktoppath=E:\Desktop
rainmeterpath=D:\Program Files\Rainmeter\Rainmeter.exe

;Dock
dockheight=30
iconsize=18

;Locations
songplace=960
chromeplace=200
cmderplace=230
binplace=40
ramplace=1450
cpuplace=1550
dayplace=1680
clockplace=1860

;Hide Elements
hidechrome=0
hidecmder=0
hidebin=0
hidetime=0
hideday=0
hidecpu=0
